#!/usr/bin/env ruby

require_relative 'azure-blobstore-concourse-resource-common'

request = JSON.parse(STDIN.read)

source = request.fetch("source")
file_match_string = request["params"]["file"]
new_file_name = request["params"]["newFileName"] # optional parameter

src_dir = ARGV[0]
Dir.chdir src_dir
matching_files = Dir.glob(file_match_string)

if matching_files.size > 1
  STDERR.puts "multiple files are matched for #{file_match_string}"
  exit 1
elsif matching_files.size == 0
  STDERR.puts "no matched file found for #{file_match_string}"
  exit 1
end

file_to_upload = matching_files.first
@storage_account_name = source["storage_account_name"]
@storage_access_key = source["storage_access_key"]
@container = source["container"]
@environment = source["environment"]
@regexp = source["regexp"]

if @storage_access_key.nil?
  STDERR.puts "PUT on public Azure blobstore container is not permitted. Please provide storage_access_key."
  exit 1
end

check_source

if new_file_name.nil?
  dest_file_name = file_to_upload
else
  dest_file_name = new_file_name
end

if @regexp.include?("/")
  dst_dir = File.dirname(source["regexp"])
  dst_path = File.join(dst_dir, File.basename(dest_file_name))
else
  dst_path = File.basename(dest_file_name)
end

response = azure_cli("upload --quiet --container #{@container} --blob #{dst_path} --file #{file_to_upload}")
metadata = []
response.each_pair {|k,v| metadata << {"name"=> k.to_s, "value"=>v.to_s }  }
puts JSON.dump({ "version" => { "path" => dst_path },
                 "metadata" => metadata
                })
